version: "3.8"
services:
  db:
    image: postgres:9.6.21-alpine
    env_file: db.env
    volumes:
      - dbdata:/var/lib/postgresql/data

  sonarqube:
    depends_on: 
      - db
    image: sonarqube:8.7.1-community
    env_file: sonarqube.env
    ports: 
      - 9000:9000
    volumes:
      - conf:/opt/sonarqube/conf
      - data:/opt/sonarqube/data
      - extensions:/opt/sonarqube/extensions
      - logs:/opt/sonarqube/logs

volumes:
  dbdata:
    name: postgres_data
    external: true
  conf: 
    name: sonarqube_conf
    external: true
  data: 
    name: sonarqube_data
    external: true
  extensions: 
    name: sonarqube_extensions
    external: true
  logs: 
    name: sonarqube_logs
    external: true  
